import {
	Sprout,
	Rocket,
	Code,
	GraduationCap,
	Coins,
	Handshake,
	MapPin,
	Landmark,
	Globe,
	Shield,
	Monitor,
	CreditCard,
	HeartPulse,
	BookOpen,
	ShoppingCart,
	Wheat,
	Leaf,
	Car,
	Home,
	Clapperboard,
	Building2,
	Heart,
	Shirt,
	Plane,
	Trophy,
	Atom,
	Factory,
	Sofa,
	TrendingUp,
	ClipboardList,
	Users,
	Lightbulb,
	Bell,
	BarChart3,
	Building,
	Briefcase,
	Star,
	FileText,
	CheckCircle,
	XCircle,
	Unlock,
	Zap,
	Lock,
	Settings,
	Save,
	Brain,
	UserCircle,
	Folder,
	Wrench,
	Search,
	Target,
	Calendar,
	Gamepad2,
	PenSquare,
	Hand,
	Check,
	X,
	AlertTriangle,
	Newspaper,
	Pencil,
	Clock,
	Frown,
	Puzzle,
	MessageCircle,
	RefreshCw,
	Eye,
	Plus,
	Hourglass,
	Circle,
	Info,
	ArrowRight,
	BarChart2,
	Send,
	ArrowLeft,
	WifiOff,
	ChevronDown,
	Loader2,
	Mail,
	ChevronLeft,
	ChevronRight,
	Trash2,
	Award,
	type LucideProps,
} from 'lucide-react';
import { type ElementType } from 'react';

const ICON_MAP: Record<string, ElementType> = {
	sprout: Sprout,
	rocket: Rocket,
	code: Code,
	'graduation-cap': GraduationCap,
	coins: Coins,
	handshake: Handshake,
	'map-pin': MapPin,
	landmark: Landmark,
	globe: Globe,
	shield: Shield,
	monitor: Monitor,
	'credit-card': CreditCard,
	'heart-pulse': HeartPulse,
	'book-open': BookOpen,
	'shopping-cart': ShoppingCart,
	wheat: Wheat,
	leaf: Leaf,
	car: Car,
	home: Home,
	clapperboard: Clapperboard,
	building2: Building2,
	heart: Heart,
	shirt: Shirt,
	plane: Plane,
	trophy: Trophy,
	atom: Atom,
	factory: Factory,
	sofa: Sofa,
	'trending-up': TrendingUp,
	'clipboard-list': ClipboardList,
	users: Users,
	lightbulb: Lightbulb,
	bell: Bell,
	'bar-chart': BarChart3,
	building: Building,
	briefcase: Briefcase,
	star: Star,
	'file-text': FileText,
	'check-circle': CheckCircle,
	'x-circle': XCircle,
	unlock: Unlock,
	zap: Zap,
	lock: Lock,
	settings: Settings,
	save: Save,
	brain: Brain,
	'user-circle': UserCircle,
	folder: Folder,
	wrench: Wrench,
	search: Search,
	target: Target,
	calendar: Calendar,
	gamepad: Gamepad2,
	'pen-square': PenSquare,
	hand: Hand,
	check: Check,
	x: X,
	'alert-triangle': AlertTriangle,
	newspaper: Newspaper,
	pencil: Pencil,
	clock: Clock,
	frown: Frown,
	puzzle: Puzzle,
	'message-circle': MessageCircle,
	'refresh-cw': RefreshCw,
	eye: Eye,
	plus: Plus,
	hourglass: Hourglass,
	circle: Circle,
	info: Info,
	'arrow-right': ArrowRight,
	'bar-chart-2': BarChart2,
	send: Send,
	'arrow-left': ArrowLeft,
	'wifi-off': WifiOff,
	'chevron-down': ChevronDown,
	'loader-2': Loader2,
	mail: Mail,
	'chevron-left': ChevronLeft,
	'chevron-right': ChevronRight,
	trash: Trash2,
	award: Award,
};

interface AppIconProps extends Omit<LucideProps, 'ref'> {
	name: string;
}

export function AppIcon({ name, ...props }: AppIconProps) {
	const IconComponent = ICON_MAP[name];
	if (!IconComponent) return null;
	return <IconComponent {...props} />;
}

export default AppIcon;
