import { Institution, Program, Event } from './types';

// ========================================
// XENTRO Mock Data
// ========================================

export const mockInstitutions: Institution[] = [
    {
        id: '1',
        name: 'TechStars Bangalore',
        type: 'accelerator',
        tagline: 'Accelerating the next generation of world-changing startups in South Asia',
        city: 'Bangalore',
        country: 'India',
        countryCode: 'IN',
        operatingMode: 'global',
        startupsSupported: 245,
        studentsMentored: 1200,
        fundingFacilitated: 150000000,
        fundingCurrency: 'USD',
        sdgFocus: ['sdg-8', 'sdg-9', 'sdg-17'],
        sectorFocus: ['ai', 'saas', 'fintech'],
        logo: '/logos/techstars.svg',
        website: 'https://techstars.com',
        linkedin: 'https://linkedin.com/company/techstars',
        description: 'TechStars Bangalore is a world-class accelerator program that helps entrepreneurs succeed. We provide access to capital, mentorship, and a global network of founders. Our 13-week program transforms promising startups into industry leaders.',
        status: 'published',
        verified: true,
        createdAt: '2024-01-15',
        updatedAt: '2024-12-01',
    },
    {
        id: '2',
        name: 'Stanford StartX',
        type: 'incubator',
        tagline: 'Where Stanford founders build the future',
        city: 'Palo Alto',
        country: 'United States',
        countryCode: 'US',
        operatingMode: 'local',
        startupsSupported: 580,
        studentsMentored: 2400,
        fundingFacilitated: 500000000,
        fundingCurrency: 'USD',
        sdgFocus: ['sdg-4', 'sdg-9'],
        sectorFocus: ['ai', 'healthtech', 'climatetech'],
        logo: '/logos/startx.svg',
        website: 'https://startx.com',
        linkedin: 'https://linkedin.com/company/startx',
        description: 'StartX is a non-profit startup accelerator for Stanford-affiliated entrepreneurs. We foster a community of founders committed to supporting each other. Our network includes 500+ companies valued at over $30B.',
        status: 'published',
        verified: true,
        createdAt: '2023-06-01',
        updatedAt: '2024-11-15',
    },
    {
        id: '3',
        name: 'IIT Delhi Innovation Hub',
        type: 'university',
        tagline: 'Transforming research into real-world impact',
        city: 'New Delhi',
        country: 'India',
        countryCode: 'IN',
        operatingMode: 'national',
        startupsSupported: 120,
        studentsMentored: 3500,
        fundingFacilitated: 25000000,
        fundingCurrency: 'USD',
        sdgFocus: ['sdg-4', 'sdg-9', 'sdg-11'],
        sectorFocus: ['edtech', 'climatetech', 'ai'],
        logo: '/logos/iitd.svg',
        website: 'https://iitd.ac.in',
        linkedin: 'https://linkedin.com/company/iitdelhi',
        description: 'The IIT Delhi Innovation Hub bridges the gap between academic research and entrepreneurship. We provide students and faculty with resources to commercialize their innovations and create lasting social impact.',
        status: 'published',
        verified: true,
        createdAt: '2023-09-01',
        updatedAt: '2024-10-20',
    },
    {
        id: '4',
        name: 'Sequoia Surge',
        type: 'vc',
        tagline: 'Building legendary companies from Day Zero',
        city: 'Singapore',
        country: 'Singapore',
        countryCode: 'SG',
        operatingMode: 'global',
        startupsSupported: 85,
        studentsMentored: 800,
        fundingFacilitated: 2000000000,
        fundingCurrency: 'USD',
        sdgFocus: ['sdg-8', 'sdg-9', 'sdg-17'],
        sectorFocus: ['saas', 'fintech', 'ai'],
        logo: '/logos/sequoia.svg',
        website: 'https://surge.sequoiacap.com',
        linkedin: 'https://linkedin.com/company/sequoia-capital',
        description: 'Sequoia Surge is a rapid scale-up program for startups in India and Southeast Asia. We combine capital with an intense 16-week program to help founders build products and teams that win.',
        status: 'published',
        verified: true,
        createdAt: '2024-02-01',
        updatedAt: '2024-12-10',
    },
    {
        id: '5',
        name: 'Tata Social Enterprise Initiative',
        type: 'csr',
        tagline: 'Empowering communities through sustainable enterprise',
        city: 'Mumbai',
        country: 'India',
        countryCode: 'IN',
        operatingMode: 'national',
        startupsSupported: 65,
        studentsMentored: 1500,
        fundingFacilitated: 50000000,
        fundingCurrency: 'INR',
        sdgFocus: ['sdg-4', 'sdg-8', 'sdg-11'],
        sectorFocus: ['social-impact', 'edtech', 'healthtech'],
        logo: '/logos/tata.svg',
        website: 'https://tata.com/csr',
        linkedin: 'https://linkedin.com/company/tata',
        description: 'The Tata Social Enterprise Initiative supports entrepreneurs who are building businesses that create positive social and environmental impact. We provide grants, mentorship, and access to the Tata network.',
        status: 'published',
        verified: true,
        createdAt: '2023-11-01',
        updatedAt: '2024-09-15',
    },
    {
        id: '6',
        name: 'Y Combinator',
        type: 'accelerator',
        tagline: 'Make something people want',
        city: 'San Francisco',
        country: 'United States',
        countryCode: 'US',
        operatingMode: 'global',
        startupsSupported: 4000,
        studentsMentored: 15000,
        fundingFacilitated: 100000000000,
        fundingCurrency: 'USD',
        sdgFocus: ['sdg-8', 'sdg-9', 'sdg-17'],
        sectorFocus: ['ai', 'saas', 'fintech', 'healthtech'],
        logo: '/logos/yc.svg',
        website: 'https://ycombinator.com',
        linkedin: 'https://linkedin.com/company/y-combinator',
        description: 'Y Combinator is a startup accelerator that provides seed funding to early-stage startups. In exchange for equity, we offer funding, mentorship, and access to a powerful network of founders and investors.',
        status: 'published',
        verified: true,
        createdAt: '2023-03-01',
        updatedAt: '2024-12-15',
    },
    {
        id: '7',
        name: 'Berlin Tech Hub',
        type: 'incubator',
        tagline: 'Europe\'s gateway to deep tech innovation',
        city: 'Berlin',
        country: 'Germany',
        countryCode: 'DE',
        operatingMode: 'national',
        startupsSupported: 180,
        studentsMentored: 900,
        fundingFacilitated: 75000000,
        fundingCurrency: 'EUR',
        sdgFocus: ['sdg-9', 'sdg-11', 'sdg-17'],
        sectorFocus: ['climatetech', 'ai', 'healthtech'],
        logo: '/logos/berlin.svg',
        website: 'https://berlintechhub.de',
        linkedin: 'https://linkedin.com/company/berlin-tech-hub',
        description: 'Berlin Tech Hub is a leading incubator for deep tech startups in Europe. We specialize in AI, sustainability, and healthcare innovation, providing founders with lab access, funding, and industry connections.',
        status: 'published',
        verified: false,
        createdAt: '2024-04-01',
        updatedAt: '2024-11-20',
    },
    {
        id: '8',
        name: 'Cambridge Innovation Centre',
        type: 'university',
        tagline: 'From lab to market, faster',
        city: 'Cambridge',
        country: 'United Kingdom',
        countryCode: 'GB',
        operatingMode: 'global',
        startupsSupported: 320,
        studentsMentored: 4200,
        fundingFacilitated: 180000000,
        fundingCurrency: 'GBP',
        sdgFocus: ['sdg-4', 'sdg-9'],
        sectorFocus: ['healthtech', 'ai', 'climatetech'],
        logo: '/logos/cambridge.svg',
        website: 'https://cam.ac.uk/innovation',
        linkedin: 'https://linkedin.com/company/cambridge-uni',
        description: 'The Cambridge Innovation Centre helps University of Cambridge researchers and students turn breakthrough discoveries into successful ventures. We offer commercialization support, investor connections, and venture building expertise.',
        status: 'published',
        verified: true,
        createdAt: '2023-08-01',
        updatedAt: '2024-10-30',
    },
];

export const mockPrograms: Program[] = [
    {
        id: '1',
        institutionId: '1',
        name: 'Cohort Spring 2025',
        description: '13-week accelerator program for B2B SaaS startups',
        duration: '13 weeks',
        type: 'accelerator',
        isActive: true,
    },
    {
        id: '2',
        institutionId: '2',
        name: 'Stanford Founders Program',
        description: 'Year-round incubation for Stanford-affiliated entrepreneurs',
        duration: '12 months',
        type: 'incubator',
        isActive: true,
    },
    {
        id: '3',
        institutionId: '4',
        name: 'Surge 10',
        description: 'Intensive 16-week program for seed-stage startups',
        duration: '16 weeks',
        type: 'accelerator',
        isActive: true,
    },
];

export const mockEvents: Event[] = [
    {
        id: '1',
        institutionId: '1',
        name: 'Demo Day 2025',
        description: 'Annual demo day showcasing cohort startups to 500+ investors',
        date: '2025-03-15',
        location: 'Bangalore, India',
        type: 'demo-day',
    },
    {
        id: '2',
        institutionId: '6',
        name: 'YC Startup School',
        description: 'Free online course for aspiring founders',
        date: '2025-02-01',
        location: 'Online',
        type: 'workshop',
    },
];

// Aggregated stats for dashboard
export const dashboardStats = {
    totalInstitutions: mockInstitutions.length,
    startupsSupported: mockInstitutions.reduce((sum, i) => sum + i.startupsSupported, 0),
    studentsMentored: mockInstitutions.reduce((sum, i) => sum + i.studentsMentored, 0),
    fundingFacilitated: mockInstitutions
        .filter(i => i.fundingCurrency === 'USD')
        .reduce((sum, i) => sum + i.fundingFacilitated, 0),
};

// Monthly institution additions (for charts)
export const institutionsByMonth = [
    { month: 'Jan', count: 1 },
    { month: 'Feb', count: 1 },
    { month: 'Mar', count: 1 },
    { month: 'Apr', count: 1 },
    { month: 'May', count: 0 },
    { month: 'Jun', count: 1 },
    { month: 'Jul', count: 0 },
    { month: 'Aug', count: 1 },
    { month: 'Sep', count: 1 },
    { month: 'Oct', count: 0 },
    { month: 'Nov', count: 1 },
    { month: 'Dec', count: 0 },
];

// Institution type distribution
export const institutionTypeDistribution = [
    { type: 'Accelerator', count: 2, color: '#2563EB' },
    { type: 'Incubator', count: 2, color: '#10B981' },
    { type: 'University', count: 2, color: '#F59E0B' },
    { type: 'VC Fund', count: 1, color: '#8B5CF6' },
    { type: 'CSR Program', count: 1, color: '#EC4899' },
];
