export const WHY_MENTOR_OPTIONS = [
	{
		value: 'mentor_startups',
		label: 'To mentor promising startups and early-stage founders',
		title: 'Mentor startups',
		description: 'Guide promising startups and early-stage founders.',
		icon: 'rocket',
	},
	{
		value: 'give_back',
		label: 'To give back to the startup ecosystem',
		title: 'Give back',
		description: 'Contribute your experience to the ecosystem.',
		icon: 'heart',
	},
	{
		value: 'discover_ideas',
		label: 'To discover innovative ideas and emerging trends',
		title: 'Discover ideas',
		description: 'Stay close to innovation and emerging trends.',
		icon: 'lightbulb',
	},
	{
		value: 'expand_network',
		label: 'To expand my professional network with founders, investors, and institutions',
		title: 'Expand network',
		description: 'Connect with founders, investors, and institutions.',
		icon: 'users',
	},
	{
		value: 'build_brand',
		label: 'To build my personal brand as a thought leader',
		title: 'Build brand',
		description: 'Establish yourself as a thought leader.',
		icon: 'star',
	},
	{
		value: 'access_deal_flow',
		label: 'To access curated, high-quality startup deal flow',
		title: 'Deal flow',
		description: 'Access curated, high-quality startup deal flow.',
		icon: 'briefcase',
	},
	{
		value: 'collaborate_mentors',
		label: 'To collaborate with other experienced mentors',
		title: 'Collaborate',
		description: 'Work alongside other experienced mentors.',
		icon: 'handshake',
	},
	{
		value: 'advisory_opportunities',
		label: 'To identify potential advisory or board opportunities',
		title: 'Advisory roles',
		description: 'Find advisory or board opportunities.',
		icon: 'target',
	},
	{
		value: 'investment_opportunities',
		label: 'To explore investment opportunities in startups',
		title: 'Invest',
		description: 'Explore investment opportunities in startups.',
		icon: 'coins',
	},
	{
		value: 'stay_engaged',
		label: 'To stay engaged with innovation and new technologies',
		title: 'Stay engaged',
		description: 'Keep up with innovation and new technologies.',
		icon: 'atom',
	},
	{
		value: 'support_students',
		label: 'To support student entrepreneurs and university-led ventures',
		title: 'Support students',
		description: 'Help student entrepreneurs and university ventures.',
		icon: 'graduation-cap',
	},
	{
		value: 'contribute_programs',
		label: 'To contribute industry expertise to structured incubation programs',
		title: 'Incubation programs',
		description: 'Lend expertise to structured incubation programs.',
		icon: 'building2',
	},
	{
		value: 'Other',
		label: 'Other',
		title: 'Other',
		description: 'Tell us your reason.',
		icon: 'pen-square',
	},
] as const;
