export { StartupProfileHero } from './StartupProfileHero';
export { PitchAboutCards } from './PitchAboutCards';
export { PitchCompetitors } from './PitchCompetitors';
export { PitchCustomers } from './PitchCustomers';
export { PitchImageTextSection } from './PitchImageTextSection';
export { PitchVisionStrategy } from './PitchVisionStrategy';
export { PitchCertifications } from './PitchCertifications';
export { TeamTabContent } from './TeamTabContent';
export { StartupSidebar } from './StartupSidebar';
export { StartupAboutSidebar } from './StartupAboutSidebar';
export type { AboutSidebarSection } from './StartupAboutSidebar';
export type { StartupWithDetails, Founder, TeamMemberData } from './types';
